@echo off
echo Starting WorkExperio Backend...
cd backend
if not exist venv (
    echo Creating virtual environment...
    python -m venv venv
)
call venv\Scripts\activate
echo Installing dependencies...
pip install -r requirements.txt
echo Initializing database...
python init_db.py
echo Starting server...
uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
pause

