"""add github fields to user

Revision ID: 7ac8b2338c6b
Revises: 204c18fc53b1
Create Date: 2025-11-09 15:33:58.045012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ac8b2338c6b'
down_revision: Union[str, Sequence[str], None] = '204c18fc53b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_project_assignments_id', table_name='project_assignments')
    op.drop_table('project_assignments')
    op.add_column('users', sa.Column('github_id', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('avatar_url', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('auth_provider', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('is_available_for_team', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('preferred_domain_id', sa.Integer(), nullable=True))
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_unique_constraint(None, 'users', ['github_id'])
    op.create_foreign_key(None, 'users', 'domains', ['preferred_domain_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'preferred_domain_id')
    op.drop_column('users', 'is_available_for_team')
    op.drop_column('users', 'auth_provider')
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'github_id')
    op.create_table('project_assignments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('project_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name='project_assignments_team_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='project_assignments_pkey')
    )
    op.create_index('ix_project_assignments_id', 'project_assignments', ['id'], unique=False)
    # ### end Alembic commands ###
